// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_SVII93P0-hnUOHe0JqPDXMASXeitDs',
    appId: '1:385662617488:web:3ee08134393d6118789515',
    messagingSenderId: '385662617488',
    projectId: 'test-937d3',
    authDomain: 'test-937d3.firebaseapp.com',
    storageBucket: 'test-937d3.firebasestorage.app',
    measurementId: 'G-W3882XP4HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAixd9ASVYMZbA-GkC8n5AihK8GO8S3NQI',
    appId: '1:385662617488:android:14e26d94a3575e12789515',
    messagingSenderId: '385662617488',
    projectId: 'test-937d3',
    storageBucket: 'test-937d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-Cq5oWLfhw0EZIQG7Dqre6UnrYWd9s8',
    appId: '1:385662617488:ios:154d3bd35f70ffe5789515',
    messagingSenderId: '385662617488',
    projectId: 'test-937d3',
    storageBucket: 'test-937d3.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-Cq5oWLfhw0EZIQG7Dqre6UnrYWd9s8',
    appId: '1:385662617488:ios:154d3bd35f70ffe5789515',
    messagingSenderId: '385662617488',
    projectId: 'test-937d3',
    storageBucket: 'test-937d3.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK_SVII93P0-hnUOHe0JqPDXMASXeitDs',
    appId: '1:385662617488:web:22419240a09cbf22789515',
    messagingSenderId: '385662617488',
    projectId: 'test-937d3',
    authDomain: 'test-937d3.firebaseapp.com',
    storageBucket: 'test-937d3.firebasestorage.app',
    measurementId: 'G-2PBMWMLCTD',
  );

}